use_frameworks!

platform :ios, '8.0'

target 'BitletSynchronizer_Example' do
  pod 'BitletSynchronizer', :path => '../../'
  
  pod 'Toast-Swift', '~> 4.0.0'
  
  pod 'Alamofire', '~> 4.7'
  pod 'AlamofireObjectMapper', '~> 5.1.0'

  target 'BitletSynchronizer_Tests' do
    inherit! :search_paths
  end
end
